### ISSUE TITLE
Model forward function seems not to update hidden state

### ISSUE THREAD

**Issue by RichardHGL** [hungthanhpham94/GRU4REC-pytorch#1]
![image](https://user-images.githubusercontent.com/20337906/51537086-7f33d680-1e88-11e9-9a58-5ee383141dbe.png)
Have a look at this. Is "hdden" a mistake for "hidden", or you just want to make recommendation through 1-step information.

**Comment by hungpthanh** [comment]
Yes, it is a typo. I meant that it is "hidden". I would fix this typo. Thank you :D 

Update: fixed
