### ISSUE TITLE
Difference from original paper: regularization term of TOP1 Loss

### ISSUE THREAD

**Issue by bilzard** [hungthanhpham94/GRU4REC-pytorch#13]
Hi.
Thank you for sharing this code.

I found difference from original paper in regularization term of TOP1 Loss.
According to the original paper, the regularization term should be calculated over only negative samples[^1].
However, this repo calculates it over all samples[^2].
It might not be significant difference, but I just pointed it out.

[^1]: https://github.com/hidasib/GRU4Rec/blob/master/gru4rec.py#L236
[^2]: https://github.com/hungthanhpham94/GRU4REC-pytorch/blob/master/lib/lossfunction.py#L89

**Comment by hungpthanh** [comment]
@bilzard Thank you for your comments!
